nats: nats://192.168.0.100:4222
nats_cluster_id: test-cluster
gateway: http://openfaas.drone.demo.gs:8080
statsd: localhost:9125
log_level: DEBUG # trace, error, info
log_format: text # json
functions:
  - name: info
    function_name: info
    message: example.info
 
  - name: echo
    # function to call when an event is received, by default it sends the message
    # payload as received unless a input_template is used
    function_name: echo
    message: example.echo
    # broadcast a message on success of the function, by default it sends the payload
    # as received unless an output template is used
    success_message: example.info.success
    templates:
      # Transform the raw message with a Go template, assumes the payload is json
      input_template: |
        {
          "subject": "{{ .JSON.subject }}"
        }
      # Transform the raw message with a Go template, assumes the payload is json
      output_template: |
          {{printf "%s" .Raw}}
  - name: tweet
    function_name: tweet
    message: pciture.new
    templates:
      input_template: |
        {
          "text": "Hey a picture from Selfi Drone #DevTernity #NomadRocks #HashiCorp",
          "image": "{{ .JSON.Data }}"
        }
