version: 2
jobs:
  test:
    docker:
      # specify the version
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nicholasjackson/pipe
    steps:
      - checkout
      - run: 
          name: Run Unit tests
          command: make test
      - run:
          name: Report code coverage
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            make coverage
            ./cc-test-reporter after-build -t gocov

  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nicholasjackson/pipe
    steps:
      - checkout
      - run: make build
  
  nats_providertest:
    docker:
      # specify the version
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nicholasjackson/pipe
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run functional tests for Nats.io provider
          command: make test_nats_provider
  
  http_providertest:
    docker:
      # specify the version
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/nicholasjackson/pipe
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Run functional tests for HTTP provider
          command: make test_http_provider

workflows:
  version: 2
  pipe:
    jobs:
      - test

      - build:
          requires:
            - test

      - nats_providertest:
          requires:
            - build

      - http_providertest:
          requires:
            - build
