# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: pipe
email: jackson.nic@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Pipe is a multi provider event router built in go, connect multiple event sources
  such as AWS SQS, Nats.io, Webhooks and pipe them together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-docs-theme

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

ui:
  header:
    color1: "#080331"
    color2: "#673051"
    trianglify: true

links:
  header:
    - title: Overview
      url: index.html
    - title: Configuration
      url: config.html
    - title: Providers
      url: providers.html

social:
  github:
    user: nicholasjackson
    repo: pipe

project:
  version: 2.0.0
  download_url: https://github.com/nicholasjackson/pipe/releases

analytics:
    google: UA-53659420-5
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
